[workspace]
members = [
    "bin/rundler",
    "bin/tools",
    "crates/rundler"
]
default-members = ["bin/rundler", "bin/tools"]

[workspace.package]
version = "0.1.0-beta"
edition = "2021"
rust-version = "1.71"
license = "MIT OR Apache-2.0"
repository = "https://github.com/alchemyplatform/rundler"

[workspace.dependencies]
anyhow = "1.0.70"
async-trait = "0.1.73"
cargo-husky = { version = "1", default-features = false, features = ["user-hooks" ] }
ethers = "2.0.8"
futures = "0.3.28"
futures-util = "0.3.28"
jsonrpsee = "0.20.1"
metrics = "0.21.0"
mockall = "0.11.4"
parse-display = "0.8.0"
pin-project = "1.0.12"
prost = "0.12.0"
serde = "1.0.160"
serde_json = "1.0.64"
rand = "0.8.5"
reqwest = { version = "0.11.18", default-features = false, features = ["rustls-tls"] }
rustls = "0.21.7"
thiserror = "1.0.40"
tokio = { version = "1.27.0", default-features = false }
