[package]
name = "super-relay"
version = "0.1.5"
edition = "2021"
description = "SuperRelay Enterprise API Gateway for Account Abstraction"
authors = ["SuperRelay Team"]

[[bin]]
name = "super-relay"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
eyre = { workspace = true }
regex = { workspace = true }

# Rundler components
rundler-builder = { path = "../../crates/builder" }
rundler-paymaster-relay = { path = "../../crates/paymaster-relay" }
rundler-pool = { path = "../../crates/pool" }
rundler-provider = { path = "../../crates/provider" }
rundler-rpc = { path = "../../crates/rpc" }
rundler-types = { path = "../../crates/types" }
secrecy = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Gateway
super-relay-gateway = { path = "../../crates/gateway" }
tokio = { workspace = true, features = ["full"] }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
