[package]
name = "super-relay"
version = "0.1.4"
edition = "2021"
description = "SuperPaymaster Enterprise Account Abstraction Relay Service"
authors = ["SuperRelay Team"]

[[bin]]
name = "super-relay"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
eyre = { workspace = true }
rundler-paymaster-relay = { path = "../../crates/paymaster-relay" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true } 
tokio = { workspace = true, features = ["full"] }
toml = { workspace = true }
tracing = { workspace = true }
