version: "3.8"

services:
  geth:
    image: ethereum/client-go:release-1.14
    ports: [ '8545:8545' ]
    command: --verbosity 1
      --http.vhosts '*,localhost,host.docker.internal'
      --http
      --http.api eth,net,web3,debug
      --http.corsdomain '*'
      --http.addr "0.0.0.0"
      --networkid 1337
      --dev
      --dev.period 0
      --allow-insecure-unlock
      --rpc.allow-unprotected-txs
      --rpc.txfeecap 0
      --dev.gaslimit 20000000

  rundler-local:
    build:
      context: ../../
      dockerfile: Dockerfile
    command: node
    depends_on:
      - geth
    ports:
      # RPC port
      - "3000:3000"
      # Metrics port
      - "8080:8080"
    environment:
      - RUST_LOG=debug
      - NETWORK=dev
      - NODE_HTTP=http://geth:8545
      - MIN_UNSTAKE_DELAY=2
      - PRIORITY_FEE_MODE_KIND=base_fee_percent
      - PRIORITY_FEE_MODE_VALUE=0
      - DISABLE_ENTRY_POINT_V0_6=true
      - DISABLE_ENTRY_POINT_V0_7=false
      - NODE_HTTP=http://geth:8545
      - RPC_API=eth,debug
      - BUILDER_PRIVATE_KEY=0x0000000000000000000000000000000000000000000000000000000000000002
