[package]
name = "rundler-paymaster-relay"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true }
anyhow = "1.0"
async-trait = "0.1"
axum = { workspace = true, features = ["macros"] }
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.0", features = ["derive"] }
ethers = { version = "2.0", features = ["abigen"] }
eyre = "0.6"
jsonrpsee = { version = "0.24", features = ["server", "macros"] }
metrics = "0.23"
metrics-exporter-prometheus = { version = "0.16", default-features = false, features = ["http-listener"] }
rundler-pool = { path = "../pool" }
rundler-sim = { path = "../sim" }
rundler-types = { path = "../types" }
secrecy = { version = "0.10", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
toml = "0.8"
tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.6", features = ["cors", "trace"] }
tracing = "0.1"
utoipa = { version = "5.2", features = ["axum_extras", "chrono"] }
utoipa-swagger-ui = { version = "8.0", features = ["axum"] }

[dev-dependencies]
anyhow = { workspace = true }
ethers = { workspace = true, features = ["ws", "rustls"] }
jsonrpsee-core = { workspace = true, features = ["client"] }
jsonrpsee-ws-client = { workspace = true }
rundler-types = { path = "../types", features = ["test-utils"] }
serde_json = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["full"] }
