[package]
name = "rundler-paymaster-relay"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true }
async-trait = { workspace = true }
ethers = { workspace = true }
eyre = { workspace = true }
jsonrpsee = { workspace = true, features = ["server", "macros", "client", "ws-client"] }
secrecy = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
toml = { workspace = true }
alloy-primitives = { workspace = true }

# --- Web framework ---
axum = { workspace = true }
rundler-pool = { path = "../pool" }
tokio = { workspace = true }

rundler-types = { path = "../types" }
serde_json = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
ethers = { workspace = true, features = ["ws", "rustls"] }
jsonrpsee-core = { workspace = true, features = ["client"] }
jsonrpsee-ws-client = { workspace = true }
rundler-types = { path = "../types", features = ["test-utils"] }
serde_json = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["full"] }
