# SuperPaymaster Policy Configuration
# This file defines sponsorship policies for different use cases

# Default policy - used when no specific policy is requested
[default]
# Allowed sender addresses (wallet addresses that can get sponsorship)
senders = [
    # Anvil test accounts (for development)
    "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",  # Account #0
    "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",  # Account #1
    "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",  # Account #2
]

# Development policy - more permissive for testing
[development]
senders = [
    # Anvil test accounts (all 10 default accounts)
    "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",  # Account #0
    "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",  # Account #1
    "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",  # Account #2
    "0x90F79bf6EB2c4f870365E785982E1f101E93b906",  # Account #3
    "0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65",  # Account #4
    "0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc",  # Account #5
    "0x976EA74026E726554dB657fA54763abd0C3a0aa9",  # Account #6
    "0x14dC79964da2C08b23698B3D3cc7Ca32193d9955",  # Account #7
    "0x23618e81E3f5cdF7f54C3d65f7FBc0aBf5B21E8f",  # Account #8
    "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720",  # Account #9
]

# Production policy - strict allowlist for mainnet
[production]
senders = [
    # Add your production wallet addresses here
    # "0x1234567890123456789012345678901234567890",
    # "0xabcdefabcdefabcdefabcdefabcdefabcdefabcd",
]

# Demo policy - for demonstration purposes
[demo]
senders = [
    # Known demo wallet addresses
    "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",  # Primary demo account
    "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",  # Secondary demo account
]

# Partner policy - for specific partners/dApps
[partner_dapp_1]
senders = [
    # Partner 1 specific addresses
    # "0xpartner1address1234567890123456789012345",
    # "0xpartner1address2345678901234567890123456",
]

# Test policy - minimal for basic testing
[test]
senders = [
    "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",  # Single test account
]

# Emergency policy - very restrictive
[emergency]
senders = [
    # Only critical addresses during emergency
    # "0xemergencyaddress123456789012345678901234",
]

# Notes:
# - Each policy section defines a set of rules for sponsorship
# - Currently only 'senders' field is supported (address allowlist)
# - Future enhancements may include:
#   - target_contracts: List of allowed contract interactions
#   - max_gas_limit: Maximum gas limit per operation
#   - daily_limits: Daily spending limits per sender
#   - time_restrictions: Time-based access controls
#   - value_limits: Maximum ETH value per operation