name: 'Build Toolchain'
description: 'Common commands for our build steps'

inputs:
  rust_components:
    description: 'Components for rust'
    required: false
    type: string
    default: ''

runs:
  using: "composite"
  steps:
    - name: Install protobuf
      run: sudo apt-get install -y protobuf-compiler
      shell: bash
    - name: Install toolchain
      uses: dtolnay/rust-toolchain@stable
      shell: bash
      with:
        toolchain: 1.71.0
        components: ${{ inputs.rust_components }}
    - uses: Swatinem/rust-cache@v2
      shell: bash
      with:
        cache-on-failure: true
    - name: Install Foundry
      shell: bash
      uses: foundry-rs/foundry-toolchain@v1

