[package]
name = "rundler-network"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rundler-types = { path = "../types" }

async-trait.workspace = true
delay_map = "0.3.0"
discv5 = { version = "0.3.1", features = ["libp2p"] }
ethereum_ssz = "0.5.3"
ethereum_ssz_derive = "0.5.3"
ethers.workspace = true
futures.workspace = true
hex = "0.4.3"
libp2p-mplex = "0.40.0"
snap = "1.1.0"
ssz_types = "0.5.4"
tokio.workspace = true
tokio-io-timeout = "1.2.0"
tokio-util = { workspace = true, features = ["codec", "compat"] }
thiserror.workspace = true
tracing.workspace = true
unsigned-varint = { version = "0.7.2", features = ["codec"] }

[dependencies.libp2p]
version = "0.52.3"
default-features = false
features = ["tokio", "noise", "macros", "tcp", "identify", "yamux", "secp256k1"]
