on:
  push:
    branches:
      - main
  pull_request:

name: compliance
jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Rundler
        uses: actions/checkout@v4
        with:
          path: rundler
          submodules: recursive

      - name: Clone Test Executor
        uses: actions/checkout@v4
        with:
          path: ./bundler-test-executors
          repository: 0xfourzerofour/bundler-test-executor

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
              
      - run: pip install jq yq

      - run: which xq

      - name: Build local docker image
        run: docker buildx build ./rundler -t alchemyplatform/rundler:latest

      - name: Run test executor
        run: ./bundler-test-executors/runall.sh ./bundler-test-executors/bundlers/rundler/rundler.yml

      - name: Parse spec results
        run: ./rundler/.github/compliance-parser.sh ./bundler-test-executors/build/out/rundler.xml
