[package]
name = "rundler-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = """
Rundler tools
"""

[dependencies]
rundler-dev = { path = "../../crates/dev" }
rundler-rpc = { path = "../../crates/rpc" }
rundler-network = { path = "../../crates/network" }

anyhow = "1.0.70"
clap = { version = "4.2.4", features = ["derive", "env"] }
dotenv = "0.15.0"
ethers = "2.0.8"
ethers-signers = {version = "2.0.8", features = ["aws"] }
hex = "0.4.3"
rusoto_core = { version = "0.48.0", default-features = false, features = ["rustls"] }
rusoto_kms = { version = "0.48.0", default-features = false, features = ["rustls"] }
serde_json = "1.0.96"
tokio.workspace = true
futures.workspace = true
enr = { version = "*", features = ["serde", "k256"] }
discv5 = { version = "0.3.1", features = ["libp2p"] }
env_logger = "0.10.0"

[dependencies.libp2p]
version = "0.52.3"
default-features = false
features = ["tokio", "identify", "noise", "macros", "ping", "tcp", "identify", "yamux", "secp256k1"]
